

export enum CardDataSource {
  TCG_PLAYER = 'TCG_PLAYER',
  EBAY_CARD_LISTING = 'EBAY_CARD_LISTING',
  POKEMON_TCG_API = 'POKEMON_TCG_API',
  TCG_COLLECTOR_WEBSITE = 'TCG_COLLECTOR_WEBSITE',
}